### ISSUE TITLE
W 4 - Submission ( But not Complete )

### ISSUE THREAD

**Issue by arahman010** [arahman010/TwitterDemo#1]
Hi, I did everything that the videos had. Thats why I did not put up any gif. Autolayout is still a mystery to me. I tried and still trying to understand and get hang of it. Besides, I had exams too so could not give as much time as it is required to. If I can do autolayout then I will commit the changes. Till then I am just notifying you guys that I did the rest as submission time is over already. Hope you will understand.  /cc @codepathreview

**Comment by avo1** [comment]
It looks like you are missing some features from the required user stories. We will need to have this completed and updated within **24hr** from this point in order for you to receive credit for the assignment.

If you need help with the these features, please reach out to your professional mentors on slack channel or post to universitysupport@codepath.com

Dave
CodePath
